# GoReleaser configuration for automated releases
# https://goreleaser.com

version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: powa-sentinel
    main: ./cmd/powa-sentinel
    binary: powa-sentinel
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.buildDate={{.Date}}

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    files:
      - README.md
      - LICENSE
      - config/config.yaml.example

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

dockers:
  - image_templates:
      - "ghcr.io/powa-team/powa-sentinel:{{ .Tag }}"
      - "ghcr.io/powa-team/powa-sentinel:latest"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--build-arg=VERSION={{.Version}}"
      - "--build-arg=COMMIT={{.ShortCommit}}"
      - "--build-arg=BUILD_DATE={{.Date}}"

release:
  github:
    owner: powa-team
    name: powa-sentinel
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"

announce:
  skip: true
